services:
  worker:
    build:
      context: ..
      dockerfile: docker/DockerfileWorker
    mem_limit: ${WORKER_MEMORY_GB}g
    memswap_limit: ${WORKER_MEMORY_GB}g
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_ENDPOINT}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET: ${MINIO_BUCKET}
      POLLING_RATE: ${POLLING_RATE_SECONDS}
    restart: unless-stopped

networks:
  default:
    name: radix
